spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            # Tự động điều hướng dựa trên domain truy cập
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

  # Cấu hình H2 Database
  datasource:
    url: jdbc:h2:file:./data/tiktokdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Cấu hình Email của Admin
app:
  admin-email: ninhquachhai0@gmail.com

groq:
  api:
    key: ${GROQ_API_KEY:YOUR_GROQ_API_KEY_HERE}

server:
  port: ${PORT:8080}
  forward-headers-strategy: native # Quan trọng khi chạy trên Render/Proxy
